#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true
export PATH=$GRAALVM_HOME/bin:$PATH

POD_LEIN_PROFILES="+uberjar"
POD_NAME="pod-babashka-gungnir"

VERSION=$(cat resources/POD_BABASHKA_GUNGNIR_VERSION)

JAR="target/pod-babashka-gungnir-$VERSION-standalone.jar"

echo "$POD_LEIN_PROFILES"

java -version
lein with-profiles "$POD_LEIN_PROFILES" "do" clean, uberjar

$GRAALVM_HOME/bin/native-image \
    -jar "$JAR" \
    -H:Name="$POD_NAME" \
    -H:+ReportExceptionStackTraces \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    "-H:IncludeResources=POD_BABASHKA_GUNGNIR_VERSION" \
     -H:ReflectionConfigurationFiles="reflection.json" \
    --initialize-at-build-time  \
    -H:Log=registerResource: \
    "-H:EnableURLProtocols=http,https" \
    "--enable-all-security-services" \
    "-H:+JNI" \
    --verbose \
    --no-fallback \
    --no-server \
    --report-unsupported-elements-at-runtime \
    --allow-incomplete-classpath \
    -Djava.library.path=$GRAALVM_HOME/jre/lib/amd64/ \
    -H:IncludeResources='.*\\.(properties|edn)' \
    -H:IncludeResources='com/ibm/icu/impl/data/icudt58b/.*' \
    -H:IncludeResources='com/ibm/icu/impl/duration/impl/data/icudt58b/.*' \
    -H:IncludeResources='com/ibm/icu/.*\\.properties' \
    -H:IncludeResources='com/github/fge/.*\\.properties' \
    -H:IncludeResources='PGMIG_VERSION' \
    --initialize-at-run-time=org.postgresql.sspi.SSPIClient \
    --initialize-at-run-time=org.postgresql.sspi.NTDSAPI \
    --initialize-at-run-time=com.sun.jna.platform.win32.Secur32 \
    --initialize-at-run-time=com.sun.jna.platform.win32.Kernel32 \
    "-J-Xmx4500m"
